---
lang: es
---

```{r, echo=FALSE, results="hide"}

```

Question
========
(2.5 puntos) La población de parásitos que infecta un árbol, en miles, evoluciona diariamente siguiendo la sucesión recursiva $x_1=2$ y $x_{n+1}=1-(2+x_n)^{-1}$ $\forall n\in\mathbb{N}$. Demostrar que la sucesión converge y calcular su límite.

Solution
========
El término recurrente de la sucesión puede escribirse de la siguiente manera

$$
x_{n+1}=1-(2+x_n)^{-1} = \frac{1+x_n}{2+x_n}\ \forall n\in\mathbb{N}.
$$

Veamos primero que la sucesión está acotada inferiormente por $0$ por inducción. $x_1=2>0$, y suponiendo $x_n>0$ se tiene que $x_{n+1} = \frac{1+x_n}{2+x_n} >0$ $\forall n\in\mathbb{N}$. 

Veamos ahora que la sucesión es decreciente también por inducción. $x_1 = 2 < x_2 = 1-(2+2)^{-1} = 3/4$. Supongamos ahora que $x_{n-1}>x_n$, entonces 

$$
\begin{gathered}
x_{n-1}>x_n \Leftrightarrow 2+x_{n-1} > 2+x_n \Leftrightarrow (2+x_{n-1})^{-1} < (2+x_n)^{-1} \\
\Leftrightarrow 1-(2+x_{n-1})^{-1} > 1-(2+x_n)^{-1} \Leftrightarrow x_{n}>x_{n+1}\ \forall n\in\mathbb{N}.
\end{gathered}
$$

Así pues, como la sucesión es monótona decreciente y está acotada inferiormente, según el [teorema de la convergencia monótona](https://aprendeconalf.es/analisis-manual/sucesiones.html#thm-convergencia-monotona), la sucesión converge.

Para calcular el límite aprovechamos la recurrencia, 

$$
x = \lim_{n\to\infty}x_n = \lim_{n\to\infty} \frac{1+x_{n-1}}{2+x_{n-1}} =\frac{1+\lim_{n\to\infty}x_{n-1}}{2+\lim_{n\to\infty}x_{n-1}} = \frac{1+x}{2+x},
$$

y resolviendo la ecuación se tiene

$$
x = \frac{1+x}{2+x} \Leftrightarrow x(2+x) = 1+x \Leftrightarrow x^2+x-1=0 \Leftrightarrow x = \frac{-1\pm \sqrt{5}}{2}.
$$

Como hemos visto que la sucesión está acotada inferiormente por $0$, podemos descartar la solución negativa, de manera que, $\lim_{n\to\infty}x_n = \frac{-1+ \sqrt{5}}{2}$.

Meta-information
================
extype: num
exname: suc-5-bio
exsolution: Solución
extol: 0.001
degree: Todos