```{r echo=FALSE, results=hide}
## DATA GENERATION

## QUESTION/ANSWER GENERATION
# sample size

```

\begin{question}
    \puntos{3.5} Un medicamento se administra por vía intravenosa a una velocidad de 15 mg/hora. Al mismo tiempo, el cuerpo metaboliza el medicamento a una velocidad del 80\% de la cantidad presente en el cuerpo por hora. 
    
    \begin{enumerate}
    -  Si el medicamento se administra de forma indefinida y suponiendo que al principio no había nada de medicamento en el cuerpo, ¿cuál será la máxima cantidad de medicamento que habrá en el cuerpo?
    -  Si el medicamento deja de administrarse después de haber administrado 150 mg, ¿cuánto tiempo tiene que pasar desde ese momento hasta que la cantidad de medicamento en el cuerpo sea 10 mg?
    \end{enumerate}
\end{question}


%% SOLUTIONS
\begin{solution}
Sea $x(t)$ la cantidad de medicamento en el cuerpo en el instante $t$.
\begin{enumerate}
-  Ecuación diferencial: $x'=15-0.8x$. Condición inicial $x(0)=0$. Solución particular: $x(t)=18.75-18.75e^{-0.8t}$ y la cantidad máxima de medicamento en el cuerpo será 18.75 mg.
-  Ecuación diferencial: $x'=-0.8x$. Condición inicial $x(0)=18.74$. Solución particular: $x(t)=18.74e^{-0.8t}$ y el tiempo que tarda en haber una cantidad de 10 mg en el cuerpo es $0.7851$ horas.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solution}
%% \exname{edo-far-2}
%% \extol{0.001}
%% \degree{Pharmacy}
 
  
