<<echo=FALSE, results=hide>>=
## DATA GENERATION
sen <- 0.91
spe <- 0.98
pre <- 0.2
## QUESTION/ANSWER GENERATION
tp <- pre*sen
fn <- pre*(1-sen)
fp <- (1-pre)*(1-spe)
tn <- (1-pre)*spe
ppv <- tp/(tp+fp)
npv <- tn/(tn+fn)
@

\begin{question}
\puntos{2.5} Se está desarrollando un test diagnóstico para detectar COVID19. Para ello, se ha realizado un estudio sobre 10000 personas, de las cuales, 850 padecían infección por COVID19. En éstas el test dio positivo en 800 de ellas. En las personas sanas el test dio positivo en el 10\% de los casos.
\begin{enumerate}
\item ¿Cuál es la sensibilidad y especificidad del test?
\item ¿Cuáles son los valores predictivos positivo y negativo? 
\item ¿Cuál es la probabilidad de que el test acierte?    
\end{enumerate}
\end{question}

%% SOLUTIONS
\begin{solution}
Sea $E$ el suceso consistente en tener la enfermedad y $+$ y $-$ los sucesos correspondientes a obtener un resultado positivo y negativo respectivamente en el test.
\begin{enumerate}
\item $VPP=\Sexpr{round(ppv,4)}$.
\item $VPN=\Sexpr{round(npv,4)}$.
\item Es más fiable para descartar la enfermedad ya que el valor predictivo negativo es mayor que el valor predictivo positivo.
\item $P(E\cap +)+P(\overline E\cap -) = \Sexpr{round(tp+tn,4)}$.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solución}
%% \exname{test-med-1}
%% \extol{0.001}
%% \degree{Medicina}
 
