<<echo=FALSE, results=hide>>=
## DATA GENERATION
sen <- 0.91
spe <- 0.98
pre <- 0.2
## QUESTION/ANSWER GENERATION
tp <- pre*sen
fn <- pre*(1-sen)
fp <- (1-pre)*(1-spe)
tn <- (1-pre)*spe
ppv <- tp/(tp+fp)
npv <- tn/(tn+fn)
@

\begin{question}
\hspace{-2.05cm}(2 pts.)\hspace{0.6cm} En una población en la que la prevalencia de una enfermedad es del 70\% se aplica un test para detectarla con una especificidad del 80\%.
¿Cuál debería ser la sensibilidad mínima del test para que si el resultado fuera negativo se descartase la enfermedad?
\end{question}

%% SOLUTIONS
\begin{solution}
Sea $E$ el suceso consistente en tener la enfermedad y $+$ y $-$ los sucesos correspondientes a obtener un resultado positivo y negativo respectivamente en el test.
\begin{enumerate}
\item $VPP=\Sexpr{round(ppv,4)}$.
\item $VPN=\Sexpr{round(npv,4)}$.
\item Es más fiable para descartar la enfermedad ya que el valor predictivo negativo es mayor que el valor predictivo positivo.
\item $P(E\cap +)+P(\overline E\cap -) = \Sexpr{round(tp+tn,4)}$.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solución}
%% \exname{test-med-1}
%% \extol{0.001}
%% \degree{Medicina}
 
