<<echo=FALSE, results=hide>>=
## DATA GENERATION
sen <- 0.91
spe <- 0.98
pre <- 0.2
## QUESTION/ANSWER GENERATION
tp <- pre*sen
fn <- pre*(1-sen)
fp <- (1-pre)*(1-spe)
tn <- (1-pre)*spe
ppv <- tp/(tp+fp)
npv <- tn/(tn+fn)
@

\begin{question}
\puntos{2.5} La prueba del reflejo rojo es un método simple y económico implementado en muchos países como una parte importante del cribado infantil de patologías oculares. Este test se aplicó a una muestra de 10000 niños, 260 de los cuales presentaban alguna patología, produciéndose 25 falsos positivos y 82 falsos negativos.
\begin{enumerate}
\item ¿Cuál es la sensibilidad y especificidad del test?
\item Según los valores predictivos, ¿para qué es mejor el test, para confirmar o para rechazar la presencia de alguna patología?
\end{enumerate}
\end{question}

%% SOLUTIONS
\begin{solution}
Sea $E$ el suceso consistente en tener la enfermedad y $+$ y $-$ los sucesos correspondientes a obtener un resultado positivo y negativo respectivamente en el test.
\begin{enumerate}
\item $VPP=\Sexpr{round(ppv,4)}$.
\item $VPN=\Sexpr{round(npv,4)}$.
\item Es más fiable para descartar la enfermedad ya que el valor predictivo negativo es mayor que el valor predictivo positivo.
\item $P(E\cap +)+P(\overline E\cap -) = \Sexpr{round(tp+tn,4)}$.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solución}
%% \exname{test-med-1}
%% \extol{0.001}
%% \degree{Medicina}
 
