<<echo=FALSE, results=hide>>=
## DATA GENERATION
fp <- 0.01
fn <- 0.002
pre <- 1 / 400
# Risks
ntd <- 2
nth <- 698
ncd <- 3
nch <- 297
## QUESTION/ANSWER GENERATION
sen <- 1 - fn / pre
spe <- 1 - fp / (1 - pre)
tp <- pre * sen
tn <- (1 - pre) * spe
ppv <- tp / (tp + fp)
npv <- tn / (tn + fn)
# Risks
nt <- ntd + nth
nc <- ncd + nch
n <- nt + nc
rt <- ntd / nt
rc <- ncd / nc
rr <- rt / rc
ot <- ntd / nth
oc <- ncd / nch
or <- ot / oc
@

\begin{question}
Un test diagnóstico para detectar una enfermedad tiene un valor predictivo positivo del 40\% y un valor predictivo negativo del 95\%. Suponiendo que la prevalencia de la enfermedad es del 10\%, se pide: 
\begin{enumerate}
\item Calcular la sensibilidad y la especificidad del test.
\item Calcular la probabilidad de un diagnóstico acertado.
\item ¿Cuál debería ser la mínima sensibilidad del test para que el test permitiese diagnosticar la enfermedad? 
\end{enumerate}
\end{question}

%% SOLUTIONS
\begin{solution}

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solución}
%% \exname{test-10-med}
%% \extol{0.001}
%% \degree{Medicine}
 
  