<<echo=FALSE, results=hide>>=
## DATA GENERATION
fp <- 0.01
fn <- 0.002
pre <- 1 / 400
# Risks
ntd <- 2
nth <- 698
ncd <- 3
nch <- 297
## QUESTION/ANSWER GENERATION
sen <- 1 - fn / pre
spe <- 1 - fp / (1 - pre)
tp <- pre * sen
tn <- (1 - pre) * spe
ppv <- tp / (tp + fp)
npv <- tn / (tn + fn)
# Risks
nt <- ntd + nth
nc <- ncd + nch
n <- nt + nc
rt <- ntd / nt
rc <- ncd / nc
rr <- rt / rc
ot <- ntd / nth
oc <- ncd / nch
or <- ot / oc
@

\begin{question}
\puntos{3.5} Un test para diagnosticar el cáncer de próstata produce un 1\% de falsos positivos y un 0.2\% de falsos negativos. Se sabe también que una población 1 cada 400 hombres sufre este tipo de cáncer.
\begin{enumerate}
\item Calcular la sensibilidad y la especificidad del test.
\item Si un hombre tiene un resultado positivo en el test, ¿cuál es la probabilidad de que tenga cáncer de próstata?
\item Calcular e interpretar el valor negativo predictivo del test.
\item ¿Es este test mejor para detectar o para descartar el cáncer de próstata?
\item Para ver si existe asociación entre el cáncer de próstata y la práctica del deporte, se tomó una muestra de 1000 hombres, de los cuales 700 practicaban deporte, y se observó que había 2 hombres con cáncer de próstata en el grupo de los que practicaban deporte y 3 hombres con cáncer de próstata en el grupo de los que no practicaban deporte. Calcular el riesgo relativo y el odds ratio de sufrir cáncer de próstata cuando se practica deporte. 
\end{enumerate}
\end{question}

%% SOLUTIONS
\begin{solution}
Sea $C$ el suceso correspondiente a sufrir cáncer de próstata y $+$ y $-$ los sucesos consistentes en tener un resultado positivo y negativo en el test respectivamente.
\begin{enumerate}
\item La sensibilidad es $P(+|D) = \Sexpr{round(sen, 4)}$ y la especificidad $P(-|\overline D) = \Sexpr{round(spe, 4)}$.
\item El valor predictivo positivo es $P(D|+) = \Sexpr{round(ppv, 4)}$.
\item El valor predictivo negativo es $P(\overline D|-) = \Sexpr{round(npv, 4)}$. 
\item Como el valor predictivo negativo es mayor que el valor predictivo positivo, el test es mejor para descartar la enfermedad que para confirmarla. De hecho el test no permite detectar la enfermedad ya que el valor predictivo positivo es menor que 0.5.
\item $RR(D)=\Sexpr{round(rr, 4)}$ y $OR(D)=\Sexpr{round(or, 4)}$. Por tanto, existe una asociación entre la práctica del deporte y el cáncer de próstata, de manera que la probabilidad de sufrir cancer de próstata cuando un hombre practica deporte es casi un cuarto de la probabilidad de sufrirlo cuando no se practica deporte, y con el odds ocurre algo similar.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solución}
%% \exname{test-med-5}
%% \extol{0.001}
%% \degree{Medicine}
 
  