<<echo=FALSE, results=hide>>=
## DATA GENERATION
sen <- 0.91
spe <- 0.98
pre <- 0.2
## QUESTION/ANSWER GENERATION
tp <- pre*sen
fn <- pre*(1-sen)
fp <- (1-pre)*(1-spe)
tn <- (1-pre)*spe
ppv <- tp/(tp+fp)
npv <- tn/(tn+fn)
@

\begin{question}
\puntos{2.5}Se recurre a cierta técnica con ultrasonidos en el proceso de diagnosis de una enfermedad.
Su sensibilidad es del \Sexpr{sen*100}\% y su especificidad del \Sexpr{spe*100}\%.
Sabiendo que la prevalencia de dicha enfermedad es del \Sexpr{pre*100}\%, se pide: 
\begin{enumerate}
\item Si a un inidividuo se le aplica la técnica y el resultado es positivo, ¿cuál es la probabilidad de que sufra esta enfermedad?
\item Si el resultado fuese negativo, ¿cuál sería la probabilidad de que no tuviera la enfermedad?
\item ¿La técnica es más fiable para confirmar la enfermedad o para descartarla? Justificar la respuesta.
\item Calcular la probabilidad de obtener un diagnóstico acertado con esta técnica.
\end{enumerate}
\end{question}


%% SOLUTIONS
\begin{solution}
Sea $E$ el suceso consistente en tener la enfermedad y $+$ y $-$ los sucesos correspondientes a obtener un resultado positivo y negativo respectivamente en el test.
\begin{enumerate}
\item $VPP=\Sexpr{round(ppv,4)}$.
\item $VPN=\Sexpr{round(npv,4)}$.
\item Es más fiable para descartar la enfermedad ya que el valor predictivo negativo es mayor que el valor predictivo positivo.
\item $P(E\cap +)+P(\overline E\cap -) = \Sexpr{round(tp+tn,4)}$.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solución}
%% \exname{test-med-1}
%% \extol{0.001}
%% \degree{Medicina}
 
