<<echo=FALSE, results=hide>>=
## DATA GENERATION
tp <- 60
fn <- 10
fp <- 80
tn <- 200
n <- tp + fn + fp + tn
pre <- 0.02
## QUESTION/ANSWER GENERATION
sen <- tp / (tp + fn)
spe <- tn / (fp + tn)
ppv <- tp / (tp + fp)
npv <- tn / (tn + fn)
ppv2 <- (pre * sen) / (pre * sen + (1 - pre) * (1 - spe))
npv2 <- ((1 -pre) * spe) / (pre * (1 - sen) + (1 - pre) * spe)
@

\begin{question}
\puntos{3   }En la siguiente tabla se muestran los resultados de un estudio para evaluar la utilidad de una tira reactiva para el diagnóstico de infección urinaria:
$$
\begin{array}{ccc}
\hline
\mbox{Resultado} & \mbox{Con infección} & \mbox{Sin infección}\\
\mbox{Positivo} & 60 & 80\\
\mbox{Negativo} & 10 & 200\\
\hline
\end{array}
$$

\begin{enumerate}
\item Calcular la sensibilidad y la especificidad del test.
\item Calcular los valores predictivos positivo y negativo del test.
¿El test es mejor para confirmar la enfermedad o para descartarla?
\item Si a partir de un estudio de prevalencia efectuado previamente conociéramos que la verdadera prevalencia de la infección urinaria en la población es del 2\%, ¿cómo se verían afectados los valores predictivos?
\end{enumerate}
\end{question}


%% SOLUTIONS
\begin{solution}
Sea $E$ el suceso consistente en tener la infección urinaria y $+$ y $-$ los sucesos correspondientes a obtener un resultado positivo y negativo respectivamente en el test.
\begin{enumerate}
\item Sensibilidad = $\Sexpr{round(sen, 4)}$ y Especificidad = $\Sexpr{round(spe, 4)}$.
\item $VPP=\Sexpr{round(ppv, 4)}$ y $VPN=\Sexpr{round(npv,4)}$. Puesto que $VPP<VPN$ el test es mejor para descartar la enfermedad.
\item $VPP=\Sexpr{round(ppv2, 4)}$ y $VPN=\Sexpr{round(npv2,4)}$. El valor predictivo positivo decrece mucho mientras el valor predictivo negativo aumenta un poco.
\end{enumerate}
\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{Solución}
%% \exname{test-med-1}
%% \extol{0.001}
%% \degree{Medicina}
 
